### ISSUE TITLE
ABBR macro to create nicknames for fuctions or macros

### ISSUE THREAD

**Issue by EuAndreh** [tarballs-are-good/quickutil#43]
```lisp
(defmacro abbr (short long &optional lambda-list)
  "Abbreviate LONG macro or function name as SHORT.
   If LAMBDA-LIST is present, also copy appropriate SETF-expander."
  `(eval-when (:compile-toplevel :execute :load-toplevel)
    (cond
      ((macro-function ',long)
       (setf (macro-function ',short) (macro-function ',long)))
      ((special-operator-p ',long)
       (error "Can't abbreviate a special-operator ~a" ',long))
      ((fboundp ',long)
       (setf (fdefinition ',short) (fdefinition ',long))
       ,(when lambda-list
          `(define-setf-expander ,short ,(append lambda-list)
             (values ,@(multiple-value-bind
                        (dummies vals store store-form access-form)
                        (get-setf-expansion
                         (cons long (remove-if (lambda (sym)
                                                 (member sym '(&optional &key)))
                                               lambda-list)))
                        (let ((expansion-vals (mapcar (lambda (x) `(quote ,x))
                                                      (list dummies
                                                            vals
                                                            store
                                                            store-form
                                                            access-form))))
                          (setf (second expansion-vals)
                                (cons 'list vals))
                          expansion-vals))))))
      (t
       (error "Can't abbreviate ~a" ',long)))
    (setf (documentation ',short 'function) (documentation ',long 'function))
    ',short))
```

Usage:
```lisp
(abbr mv-bind multiple-value-bind)
```
...and both will work identically the same.

Provides: ABBR
Requires: nothing
Author: https://github.com/vseloved/rutils/blob/master/AUTHORS
License: https://github.com/vseloved/rutils/blob/master/LICENSE

**Comment by tarballs-are-good** [comment]
I added it, but then realized the license is not public domain. So I had to revert it.

Sorry. If @vseloved would like to provide it as public domain, then I would be happy to include it.

**Comment by vseloved** [comment]
Hi, I don't have anything against including it here. I thought that the MIT license is permissive enough for such things. Moreover, it seems that the `quickutil` license is also an MIT, right? However, if something else is needed I can, probably, do that...

**Comment by tarballs-are-good** [comment]
MIT is technically permissive enough; it definitely is for me. The only reason only Public Domain is supported right now is because individual utilities don't have license information attached to them. If someone were to generate a stand-alone utility file (as supported by Quickutil), then they would need to add the copyright/license info required by an MIT license. This isn't done at all, at the moment.

**Comment by PuercoPop** [comment]
Would a valid way to handle this be to add the Copyright information to the docstring?
