### ISSUE TITLE
defaccessor

### ISSUE THREAD

**Issue by cl-porky11** [tarballs-are-good/quickutil#47]
(defmacro defaccessor (name lambda-list &body body)
      (with-gensyms (value)
        `(progn
           (defun ,name ,lambda-list
             ,@body)
           (defun (setf ,name) ,(cons value lambda-list)
             ,@(butlast body)
             (setf ,@(last body) ,value)))))

Provides: defaccessor
Requires:
Author: me
License: Public Domain

Defines a function and makes it setf-able.
The last expression of the function has to be setfable.
If there is more than one expression in the body, both functions will do the same things except with the last

**Comment by tarballs-are-good** [comment]
I like this, but I propose a slightly different variant. Let me write the variant, and I'll get back to you. :)

**Comment by tarballs-are-good** [comment]
I added a version of this. See the commit/doc string. :)
