### ISSUE TITLE
construct

### ISSUE THREAD

**Issue by cl-porky11** [tarballs-are-good/quickutil#48]
(defun applyable (fun)
      (lambda (&rest args)
        (funcall fun args)))

    (defun applying (fun)
      (lambda (arg)
        (apply fun arg)))

    (defun construct (fun &rest funs)
      (lambda (&rest args)
        (apply fun
               (mapcar (lambda (fun) (apply fun args)) funs))))

Provides: applyable applying construct
Requires:
Author: me
License: Public Domain

`applyable` takes a function that is able to take a single arument of type list and evaluates to a function that takes this list as argument list.

`applying` takes a function that is able to take some arguments and evaluates to a function that takes these arguments as single list.

`construct` takes a function and some other functions and returns a function that calls every of the other functions with the argumets of the new function and applies the results to the first function.
It can be compared to J's ability of using operators on operators.

Example: Creating a function that calculates the average of the arguments:

    (construct '/ '+ (applyable 'length))
Sums arguments, calculates the number of arguments, then divides the sum through the number of arguments.

    (construct '/ (applying '+) 'length)
Similar, but takes a single list of numbers instead of multiple arguments.

**Comment by tarballs-are-good** [comment]
I changed the name `CONSTRUCT` to `COMPOSE-APPLY`. Is that OK?

**Comment by cl-porky11** [comment]
when it's called `compose-apply` one may think you use it like apply (with a list as last argument: `(compose-apply fun fun1 (list fun2 fun3)`), but it's used like funcall (`(funcall fun fun1 fun2 fun3)`)
