### ISSUE TITLE
recursive-find/collect

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [tarballs-are-good/quickutil#49]
;; Write the code here.
    
    (defun recursive-find/collect (predicate tree)
      "Returns a list of every node in the TREE that satisfies the PREDICATE. If there are any improper lists in the tree, the PREDICATE is also applied to their dotted elements."
      (let ((sentinel (gensym)))
        (flet ((my-cdr (obj)
                 (cond ((consp obj)
                        (let ((result (cdr obj)))
                          (if (listp result)
                              result
                              (list result sentinel))))
                       (t
                        (list sentinel)))))
          (loop for (item . rest) on tree by #'my-cdr
             until (eq item sentinel)
               if (funcall predicate item) collect item
               else if (listp item) append (recursive-find/collect predicate item)))))

Provides: recursive-find/collect
Requires: Common Lisp
Author: Jeremy Phelps <phelpsj@nuvox.net>
License: Public Domain

**Comment by tarballs-are-good** [comment]
I added it as TREE-COLLECT. Is that OK?

Thanks!
