### ISSUE TITLE
SIFT (new utility) - Separate the wheat from the chaff.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [tarballs-are-good/quickutil#50]
(defun sift (predicate list)
       "Returns two values from the LIST: A list of values that satisfy the PREDICATE,
    and a list of those that don't."
       (loop for item in list
            if (funcall predicate item) collect item into gold
            else collect item into dirt
           finally (return (values gold dirt))))
Provides: sift
Requires: Nothing
Author: Jeremy Phelps
License: Public Domain

**Comment by tarballs-are-good** [comment]
Hello! Thanks for the submission. Have you seen [`partition-if`](http://quickutil.org/list?q=partition-if)?

**Comment by tarballs-are-good** [comment]
I'm going to close. Please re-open if I missed something!
